<!DOCTYPE html>
<html>
    <head>
        <title>Privacy Policy | JK Travel Trails</title>
        <link rel="icon" type="image/x-icon" href="Logos/JK TRAVELS.png">


        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="styles/styles.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    </head>
    <body style="position: relative;">

        <!-- Header -->
            <header class="header">
              <div class="navbar">
                <a href="home.php"><img class="logo" src="Logos/JK TRAVELS.png"></a>
                <ul class="links">
                  <li><a href="home.php">Home</a></li>
                  <li><a href="AboutUs.php">About</a></li>
                  <li><a href="safarisUganda.php">Safaris</a></li>
                  <li><a href="experiences.php">Experiences</a></li>
                  <li><a href="blog.php">Blog</a></li>
                </ul>
                
                <a class="action_btn2" aria-label="chat on WhatsApp" href="https://wa.me/256780433746" style="color: white;"> <i class="fa-brands fa-whatsapp"></i> Lets Chat</a>
                <a href="contact.php" class="action_btn" style="color: white;">Contact Us</a>
                <div class="toggle_btn">
                  <i class="fa-solid fa-bars"></i>
                </div>
              </div>

              <div class="dropdown_menu">
                <li><a href="home.php">Home</a></li>
                <li><a href="AboutUs.php">About</a></li>
                <li><a href="safarisUganda.php">Safaris</a></li>
                <li><a href="experiences.php">Experiences</a></li>
                <li><a href="gallery.php">Gallery</a></li>
                <li><a href="blog.php">Blog</a></li>
                <li><a href="contact.php" class="action_btn">Contact Us</a></li>
                
              </div>

            </header>

            <script>
                const toggleBtn = document.querySelector('.toggle_btn')
                const toggleBtnIcon = document.querySelector('.toggle_btn i')
                const dropDownMenu = document.querySelector('.dropdown_menu')

                toggleBtn.onclick = function () {
                    dropDownMenu.classList.toggle('open')

                    // CODE FOR THE 'X' MARK ON THE DROPDOWN MENU
                    const isOpen = dropDownMenu.classList('open')

                    toggleBtnIcon.classList = isOpen
                    ? 'fa-solid fa-xmark'
                    : 'fa-solid fa-bars'
                }
            </script>
          <!-- End -->
           <main>
            
            <div class="title">
                <h1>Privacy Policy</h1>
                <p>.......UPDATED: 04TH SEPTEMBER 2023</p>
            </div>
            <div class="protection-content">
                <p>

                <strong>JK Travel Trails Privacy Policy</strong><br>

                Effective date: July 25, 2024<br><br>

                JK Travel Trails (“us”, “we”, or “our”) operates the https://jktraveltrails.com/ and JK Travel Trails enewsletter (the “Service”).<br><br>

                This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices
                you have associated with that data.<br><br>

                We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.<br><br>

                <strong>Definitions</strong><br><br>

                <strong>Service</strong><br>
                Service is the https://jktaveltrails.com website and JK Travel Trails enewsletter operated by JK Travel Trails<br><br>

                <b>Personal Data</b><br>
                Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).<br><br>

                <b>Usage Data</b><br>
                Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).<br><br>

                <b>Cookies</b>
                Cookies are small pieces of data stored on your device (computer or mobile device).<br><br>

                <b>Data Controller</b><br>
                Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.
                For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.<br><br>

                <b>Data Processors (or Service Providers)</b><br>
                Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.
                We may use the services of various Service Providers in order to process your data more effectively.<br><br>

                <b>Data Subject (or User)</b><br>
                Data Subject is any living individual who is using our Service and is the subject of Personal Data.<br><br>

                <b>Information Collection And Use</b>
                We collect several different types of information for various purposes to provide and improve our Service to you.<br><br>

                <b>Types of Data Collected</b><br><br>

                <b>Personal Data</b><br>
                While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:<br><br>

                &bull; Business and/or Personal Email address<br>
                &bull; First name and last name<br>
                &bull; Phone number<br>
                &bull; Business Name and Address, State, Province, ZIP/Postal code, City<br>
                &bull; Business Title<br>
                &bull; Consortia and/or Industry Affiliation<br>
                &bull; Personal Name and Address, State, Province, ZIP/Postal code, City<br>
                &bull; Cookies and Usage Data<br><br>
                We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.<br><br>

                <b>Usage Data</b><br>
                We may also collect information about how the Service is accessed and used (“Usage Data”). This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.<br><br>

                <b>Tracking Cookies Data</b><br>
                We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
                Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your
                browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect
                and track information and to improve and analyze our Service.<br><br>

                You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
                However, if you do not accept cookies, you may not be able to use some portions of our Service.<br><br>

                Examples of Cookies we use:<br><br>

                &bull; Session Cookies. We use Session Cookies to operate our Service.<br>
                &bull; Security Cookies. We use Security Cookies for security purposes.<br><br>
                <b>Use of Data</b><br>
                JK Travel Trails uses the collected data for various purposes:<br><br>

                &bull; To provide and maintain our Service<br>
                &bull; To notify you about changes to our Service<br>
                &bull; To allow you to participate in interactive features of our Service when you choose to do so<br>
                &bull; To provide customer support<br>
                &bull; To gather analysis or valuable information so that we can improve our Service<br>
                &bull; To monitor the usage of our Service<br>
                &bull; To detect, prevent and address technical issues<br>
                &bull; To provide you with news, special offers and general information about goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information<br><br>
                
                <b>Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</b><br>
                If you are from the European Economic Area (EEA), JK Travel Trails legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.<br><br>

                JK Travel Trails may process your Personal Data because:<br><br>

                &bull; We need to perform a contract with you<br>
                &bull; You have given us permission to do so<br>
                &bull; The processing is in our legitimate interests and it’s not overridden by your rights<br>
                &bull; To comply with the law<br><br>
                <b>Retention of Data</b><br>
                JK Travel Trails will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                JK Travel Trails will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                <br><br>
                <b>Transfer Of Data</b><br>
                Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.<br><br>

                Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.<br><br>

                JK Travel Trails will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.<br><br>

                <b>Disclosure Of Data</b><br>

                <b>Business Transaction</b><br>
                If JK Travel Trails is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
                Disclosure for Law Enforcement<br><br>

                Under certain circumstances, JK Travel Trails may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).<br><br>

                <b>Legal Requirements</b><br>
                JK Travel Trails may disclose your Personal Data in the good faith belief that such action is necessary to:<br><br>

                &bull; To comply with a legal obligation<br>
                &bull; To protect and defend the rights or property of JK Travel Trails <br>
                &bull; To prevent or investigate possible wrongdoing in connection with the Service<br>
                &bull; To protect the personal safety of users of the Service or the public<br>
                &bull; To protect against legal liability. <br><br>
                
                <b>Security Of Data</b><br>
                The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.<br><br>

                <b>“Do Not Track” Signals</b>
                We do not support Do Not Track (“DNT”). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.<br><br>

                You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.

                <b>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</b><br>
                If you are a resident of the European Economic Area (EEA), you have certain data protection rights. JK Travel Trails aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.<br><br>

                If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact our office at Tel: +256 (0) 780 433 746 or email  <a href="mailto:marketing@jktraveltrails.com">marketing@jktraveltrails.com</a><br><br>

                In certain circumstances, you have the following data protection rights:<br><br>

                <b>The right to access, update or to delete the information we have on you.</b> To access, update or request deletion of your Personal Data, please contact marketing@jktraveltrails.com<br><br>

                <b>The right of rectification.</b> You have the right to have your information rectified if that information is inaccurate or incomplete.<br><br>

                <b>The right to object.</b> You have the right to object to our processing of your Personal Data.<br><br>

                <b>The right of restriction.</b> You have the right to request that we restrict the processing of your personal information.<br><br>

                <b>The right to data portability.</b> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.<br><br>

                <b>The right to withdraw consent.</b> You also have the right to withdraw your consent at any time where Volcanoes Safaris relied on your consent to process your personal information.<br><br>

                Please note that we may ask you to verify your identity before responding to such requests.
                You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).<br><br>

                <b>Service Providers</b><br>
                We may employ third party companies and individuals to facilitate our Service (“Service Providers”), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.<br><br>

                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.<br><br>

                <b>Analytics</b><br>
                We may use third-party Service Providers to monitor and analyze the use of our Service.<br><br>

                <b>Google Analytics</b><br>
                Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.<br><br>

                You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. The add-on prevents the Google Analytics JavaScript (ga.js, analytics.js, and dc.js) from sharing information with Google Analytics about visits activity.

                For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: http://www.google.com/intl/en/policies/privacy/<br><br>

                <b>Email Marketing</b><br><br>
                We may use third-party Service Providers to provide you with news, special offers and general information about our goods, services and events.<br><br>

                <b>Mailchimp</b><br>
                MailChimp is an online marketing platform that enables members to send and manage email campaigns and serve advertisements.
                They also provide real-time data analytics. Volcanoes Safaris utilizes Mailchimp to store Personal Data and deliver emails
                to provide you with news, special offers and general information about our goods, services and events.<br><br>

                You can opt-out of receiving any, or all, communications from JK Travel Trils by following the unsubscribe link or instructions provided in any email we send.<br><br>

                For more information on the privacy policy practices of Mailchimp, please visit the Mailchimp Privacy Terms web page: https://mailchimp.com/legal/privacy/

                <b>Customer Relationship Management Tool</b><br>
                We may use third-party Service Providers to securely store and maintain your Personal Data of a business nature.<br><br>

                <b>Links To Other Sites</b><br><br>

                Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.<br><br>

                We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.<br><br>

                <b>Children’s Privacy</b><br>
                Our Service does not address anyone under the age of 18 (“Children”).<br><br>

                We do not knowingly collect personally identifiable information from anyone under the age of 18.
                If you are a parent or guardian and you are aware that your Children has provided us with Personal
                Data, please contact us. If we become aware that we have collected Personal Data from children without
                verification of parental consent, we take steps to remove that information from our servers.<br><br>

                <b>Changes To This Privacy Policy</b><br>
                We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.<br><br>

                We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.<br><br>

                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.<br><br>

                <b>Contact Us</b><br>
                If you have any questions about this Privacy Policy, please contact us:<br><br>

                &bull; By email: marketing@jktraveltrails.com<br>
                &bull; By phone: +256 (0) 780 433 746<br>
                &bull; By mail: JK Travel Trails, Gratel Magil, Bukoto, Kampala, Uganda
                </p>


            </div>
           
           <!-- News letter -->
        <div class="Nl-container">
            <form action="">
              <h1>Join Our Newsletter</h1>
              <p>Stay in touch, Connected and Updated</p>
              <div class="email-box">
                <i class="fa-solid fa-envelope"></i>
                <input class="tbox" type="email" name="" value="" placeholder="Enter your email" id="" required>
                <button class="Nl-btn" type="submit" name="button" value="submit">Subscribe</button>
              </div>
            </form>
          </div>
  
          <!-- News letter End -->
  
        </main>
        <footer>
            <div class="footer-grid">
              <div class="footer-left">
                <h3>Connect with US</h3>
                <p>Write to us on <a href="mailto:inquiries@jktaveltrails.com">enquiries@jktaveltrails.com</a> or send us a message
                  via the form on our <a href="contact.php">contact us page</a>. <br>
                  You can call Us on:<br>
                  <strong>Uganda:</strong> +256 (0) 780 433 746<br>
                  <strong>Uganda:</strong> +256 (0) 705 145 554<br>
                  You can also chat to one of our sales consultants via our Lets Chat
                  button.          
                </p>            
                <p class="socials-footer">
                  <a href="https://x.com/jktraveltrails"><i class="fa-brands fa-x-twitter"></i></a>
                  <a href="https://www.instagram.com/jktraveltrails?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=="><i class="fa-brands fa-instagram"></i></a>
                  <a href="https://wa.me/256780433746"><i class="fa-brands fa-whatsapp"></i></a>
                  <a href="https://www.youtube.com/channel/UCjvwDzr3z6bqXnNsc8_7VDw"><i class="fa-brands fa-youtube"></i></a>
                </p>
              </div>
                  <!--footer menu-->
              <div class="footer-middle">
                <h3>Quick links</h3><br>
              <div class="link-container">
                <a href="home.php">Home</a>
                <a href="AboutUs.php">About</a>
                <a href="safarisUganda.php">Safaris</a>
                <a href="experiences.php">Experiences</a>
                <a href="contact.php">Contact</a>
                <a href="blog.php">Blog</a>
              </div><br>
            </div>
            <div class="footer-right">
              <h3>Useful information</h3><br>
              <div class="link-container">
                <a href="faqs.php">Frequently Asked Questions</a>
                <a href="terms-and-conditions.php">Terms and conditions</a>
                <a href="privacy-policy.php">Privacy Policy</a>
                <a href="protection.php">Your Protection</a>
                <a href="payment.php">Make a Payment</a>
                <a href="mailto:inquiries@jktraveltrails.com">New Question</a>
              </div>
            </div>
            </div>
                
          <div class="footer-bottom">
          <hr> <hr>
          <p class="footer-words">copyright © <script>document.write(new Date().getFullYear())</script> <strong>JK Travel Trails. </strong>All Rights Reserved</p>
          </div>     
          </footer>






    </body>

</html>